RLP_version = 2
Run_loot_table = {
----- Ewü  2022/02/10 P2 Loot
----- Lome 2022/02/11 P3 Loot
-----
-----SSC
-----Trashloot
{["loot_id"] = "30021", ["loot_name"] = "Wildfury Greatstaff", ["prio"] = "Prio: Feral",},
{["loot_id"] = "30027", ["loot_name"] = "Boots of Courage Unending", ["prio"] = "Prio: DPS Warrior > Ret > Enha",},
{["loot_id"] = "30022", ["loot_name"] = "Pendant of the Perilous", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30620", ["loot_name"] = "Spyglass of the Hidden Fleet", ["prio"] = "Prio: PvP Players",},
{["loot_id"] = "30025", ["loot_name"] = "Serpentshrine Shuriken", ["prio"] = "Prio: Prot Warrior > DPS Warrior > Rogue",},
-----Hydross
{["loot_id"] = "30629", ["loot_name"] = "Scarab of Displacement", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30047", ["loot_name"] = "Blackfathom Warbands", ["prio"] = "Prio: Holy Pala > Resto Shaman",},
{["loot_id"] = "30048", ["loot_name"] = "Brighthelm of Justice", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30052", ["loot_name"] = "Ring of Lethality", ["prio"] = "Prio: Hunter/Rogue > any Melee",},
{["loot_id"] = "30050", ["loot_name"] = "Boots of the Shifting Nightmare", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30049", ["loot_name"] = "Fathomstone", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32516", ["loot_name"] = "Wraps of Purification", ["prio"] = "Prio: Priest",},
{["loot_id"] = "30664", ["loot_name"] = "Living Root of the Wildheart", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30055", ["loot_name"] = "Shoulderpads of the Stranger", ["prio"] = "Prio: Enha > Ret > Arms > Rogue",},
{["loot_id"] = "33055", ["loot_name"] = "Band of Vile Aggression", ["prio"] = "Prio: Feral > Prot Warri",},
{["loot_id"] = "30054", ["loot_name"] = "Ranger-General's Chestguard", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30056", ["loot_name"] = "Robe of Hateful Echoes", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30053", ["loot_name"] = "Pauldrons of the Wardancer", ["prio"] = "Prio: Arms > Ret",},
-----Lurker
{["loot_id"] = "30061", ["loot_name"] = "Ancestral Ring of Conquest", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30059", ["loot_name"] = "Choker of Animalistic Fury", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30065", ["loot_name"] = "Glowing Breastplate of Truth", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30062", ["loot_name"] = "Grove-Bands of Remulos", ["prio"] = "Prio: Resto Druid",},
{["loot_id"] = "30058", ["loot_name"] = "Mallet of the Tides", ["prio"] = "Prio: Prot Warrior",},
{["loot_id"] = "33054", ["loot_name"] = "The Seal of Danzalar", ["prio"] = "Prio: Prot Paladin",},
{["loot_id"] = "30064", ["loot_name"] = "Cord of Screaming Terrors", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30060", ["loot_name"] = "Boots of Effortless Striking", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30665", ["loot_name"] = "Earring of Soulful Meditation", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30066", ["loot_name"] = "Tempest-Strider Boots", ["prio"] = "Prio: Resto Shaman",},
{["loot_id"] = "30067", ["loot_name"] = "Velvet Boots of the Guardian", ["prio"] = "Prio: Arcane Mage > Ele",},
{["loot_id"] = "30057", ["loot_name"] = "Bracers of Eradication", ["prio"] = "Prio: Ret/Fury/Arms",},
-----Leotheras
{["loot_id"] = "30240", ["loot_name"] = "Gloves of the Vanquished Defender", ["prio"] = "Prio: Feral > Holy Priest > Prot Warri/Balance > Resto Druid > Dps Warri > Shadow",},
{["loot_id"] = "30239", ["loot_name"] = "Gloves of the Vanquished Champion", ["prio"] = "Prio: Rogues > Prot > Enha",},
{["loot_id"] = "30241", ["loot_name"] = "Gloves of the Vanquished Hero", ["prio"] = "Prio: Mage > Hunter",},
{["loot_id"] = "30097", ["loot_name"] = "Coral-Barbed Shoulderpads", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30095", ["loot_name"] = "Fang of the Leviathan", ["prio"] = "Prio: Warlocks > Prot Paladin",},
{["loot_id"] = "30092", ["loot_name"] = "Orca-Hide Boots", ["prio"] = "Prio: Resto Druid > Resto Shaman",},
{["loot_id"] = "30091", ["loot_name"] = "True-Aim Stalker Bands", ["prio"] = "Prio: Enha > Hunter",},
{["loot_id"] = "30627", ["loot_name"] = "Tsunami Talisman", ["prio"] = "Prio: Feral > Fury/Arms",},
{["loot_id"] = "30096", ["loot_name"] = "Girdle of the Invulnerable", ["prio"] = "Prio: Prot Warrior > Prot Paladin",},
-----Karathress
{["loot_id"] = "30246", ["loot_name"] = "Leggings of the Vanquished Defender", ["prio"] = "Prio: Feral > Holy Priest > Prot Warri/Balance > Resto Druid > Dps Warri > Shadow",},
{["loot_id"] = "30245", ["loot_name"] = "Leggings of the Vanquished Champion", ["prio"] = "Prio: Prot > Rogue > Ele > Enha > Holy > Resto > Ret",},
{["loot_id"] = "30247", ["loot_name"] = "Leggings of the Vanquished Hero", ["prio"] = "Prio: Mage > Warlock",},
{["loot_id"] = "30101", ["loot_name"] = "Bloodsea Brigand's Vest", ["prio"] = "Prio: DPS Warrior > Rogue",},
{["loot_id"] = "30663", ["loot_name"] = "Fathom-Brooch of the Tidewalker", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30099", ["loot_name"] = "Frayed Tether of the Drowned", ["prio"] = "Prio: Prot Warrior",},
{["loot_id"] = "30100", ["loot_name"] = "Soul-Strider Boots", ["prio"] = "Prio: Holy Priest > Resto Druid",},
{["loot_id"] = "30626", ["loot_name"] = "Sextant of Unstable Currents", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30090", ["loot_name"] = "World Breaker", ["prio"] = "Prio: FFA",},
-----Morogrim
{["loot_id"] = "33058", ["loot_name"] = "Band of the Vigilant", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30098", ["loot_name"] = "Razor-Scale Battlecloak", ["prio"] = "Prio: Ret > Enha",},
{["loot_id"] = "30081", ["loot_name"] = "Warboots of Obliteration", ["prio"] = "Prio: Fury/Arms/Ret > Prot Warrior",},
{["loot_id"] = "30085", ["loot_name"] = "Mantle of the Tireless Tracker", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30084", ["loot_name"] = "Pauldrons of the Argent Sentinel", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30083", ["loot_name"] = "Ring of Sundered Souls", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30720", ["loot_name"] = "Serpent-Coil Braid", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30082", ["loot_name"] = "Talon of Azshara", ["prio"] = "Prio: Rogue > Fury",},
{["loot_id"] = "30075", ["loot_name"] = "Gnarled Chestpiece of the Ancients", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30068", ["loot_name"] = "Girdle of the Tidal Call", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30079", ["loot_name"] = "Illidari Shoulderpads", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30080", ["loot_name"] = "Luminescent Rod of the Naaru", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30008", ["loot_name"] = "Pendant of the Lost Ages", ["prio"] = "Prio: PvP Players",},
-----Lady Vashj
{["loot_id"] = "30242", ["loot_name"] = "Helm of the Vanquished Champion", ["prio"] = "Prio: Rogue > Enhancer > Resto/Holy/Ret > Prot/Ele",},
{["loot_id"] = "30244", ["loot_name"] = "Helm of the Vanquished Hero", ["prio"] = "Prio: Mage > Hunter > Warlock",},
{["loot_id"] = "30243", ["loot_name"] = "Helm of the Vanquished Defender", ["prio"] = "Prio: Feral > Resto Druid > Balance/Holy Priest > DPS Warri > Prot Warri/Shadow",},
{["loot_id"] = "30111", ["loot_name"] = "Runetotem's Mantle", ["prio"] = "Prio: Resto Druid",},
{["loot_id"] = "30110", ["loot_name"] = "Coral Band of the Revived", ["prio"] = "Prio: Priest/Druid > Shaman/Paladin",},
{["loot_id"] = "30112", ["loot_name"] = "Glorious Gauntlets of Crestfall", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30109", ["loot_name"] = "Ring of Endless Coils", ["prio"] = "Prio: Warlock > Ele/Balance > Shadow > Mage",},
{["loot_id"] = "30107", ["loot_name"] = "Vestments of the Sea-Witch", ["prio"] = "Prio: Warlock > Ele > Mage",},
{["loot_id"] = "30106", ["loot_name"] = "Belt of One-Hundred Deaths", ["prio"] = "Prio: Feral > Ret > Enha > Rogue/DPS Warrior",},
{["loot_id"] = "30104", ["loot_name"] = "Cobra-Lash Boots", ["prio"] = "Prio: Hunter > Enha/Ret",},
{["loot_id"] = "30103", ["loot_name"] = "Fang of Vashj", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30102", ["loot_name"] = "Krakken-Heart Breastplate", ["prio"] = "Prio: Ret > Arms",},
{["loot_id"] = "30105", ["loot_name"] = "Serpent Spine Longbow", ["prio"] = "Prio: Hunter",},
{["loot_id"] = "30108", ["loot_name"] = "Lightfathom Scepter", ["prio"] = "Prio: Resto Shaman/Pala > Druid/Priest",},
{["loot_id"] = "30621", ["loot_name"] = "Prism of Inner Calm", ["prio"] = "Prio: FFA",},
-----
-----The Eye
-----Thrashloot
{["loot_id"] = "30030", ["loot_name"] = "Girdle of Fallen Stars", ["prio"] = "Prio: Resto Shaman > Holy Pala",},
{["loot_id"] = "30026", ["loot_name"] = "Bands of the Celestial Archer", ["prio"] = "Prio: Hunter > Enha",},
{["loot_id"] = "30029", ["loot_name"] = "Bark-Gloves of Ancient Wisdom", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30020", ["loot_name"] = "Fire-Cord of the Magus", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30024", ["loot_name"] = "Mantle of the Elven Kings", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30028", ["loot_name"] = "Seventh Ring of the Tirisfalen", ["prio"] = "Prio: Prot Paladin",},
-----Al'ar
{["loot_id"] = "29949", ["loot_name"] = "Arcanite Steam-Pistol", ["prio"] = "Prio: Hunter > Rogue",},
{["loot_id"] = "29922", ["loot_name"] = "Band of Al'ar", ["prio"] = "Prio: Shadow/Prot Pala",},
{["loot_id"] = "29921", ["loot_name"] = "Fire Crest Breastplate", ["prio"] = "Prio: FFA",},
{["loot_id"] = "29947", ["loot_name"] = "Gloves of the Searing Grip", ["prio"] = "Prio: Ret > Prot Warri > DPS Warri > Feral",},
{["loot_id"] = "29918", ["loot_name"] = "Mindstorm Wristbands", ["prio"] = "Prio: FFA",},
{["loot_id"] = "29920", ["loot_name"] = "Phoenix-Ring of Rebirth", ["prio"] = "Prio: Resto Shaman/Holy Pala",},
{["loot_id"] = "29925", ["loot_name"] = "Phoenix-Wing Cloak", ["prio"] = "Prio: Prot Warri > Prot Pally",},
{["loot_id"] = "30447", ["loot_name"] = "Tome of Fiery Redemption", ["prio"] = "Prio: FFA",},
{["loot_id"] = "29924", ["loot_name"] = "Netherbane", ["prio"] = "Prio: Enhancer",},
{["loot_id"] = "29923", ["loot_name"] = "Talisman of the Sun King", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30448", ["loot_name"] = "Talon of Al'ar", ["prio"] = "Prio: FFA",},
{["loot_id"] = "29948", ["loot_name"] = "Claw of the Phoenix", ["prio"] = "Prio: Hunter",},
{["loot_id"] = "32944", ["loot_name"] = "Talon of the Phoenix", ["prio"] = "Prio: Enhancer > Fury",},
-----Void Reaver
{["loot_id"] = "30248", ["loot_name"] = "Pauldrons of the Vanquished Champion", ["prio"] = "Prio: Rogue > Holy Pala > Resto Shaman",},
{["loot_id"] = "30250", ["loot_name"] = "Pauldrons of the Vanquished Hero", ["prio"] = "Prio: 	Mage > Hunter",},
{["loot_id"] = "30249", ["loot_name"] = "Pauldrons of the Vanquished Defender", ["prio"] = "Prio: Feral > Prot Warri > Holy Priest > Balance > Resto Druid > DPS Warri > Shadow",},
{["loot_id"] = "29984", ["loot_name"] = "Girdle of Zaetar", ["prio"] = "Prio: 	Resto Druid",},
{["loot_id"] = "32515", ["loot_name"] = "Wristguards of Determination", ["prio"] = "Prio: Prot Pala",},
{["loot_id"] = "30619", ["loot_name"] = "Fel Reaver's Piston", ["prio"] = "Prio: FFA",},
{["loot_id"] = "29983", ["loot_name"] = "Fel-Steel Warhelm", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30450", ["loot_name"] = "Warp-Spring Coil", ["prio"] = "Prio: FFA",},
{["loot_id"] = "29986", ["loot_name"] = "Cowl of the Grand Engineer", ["prio"] = "Prio: Shadow",},
{["loot_id"] = "29985", ["loot_name"] = "Void Reaver Greaves", ["prio"] = "Prio: SV Hunter > BM Hunter",},
-----Solarian
{["loot_id"] = "29950", ["loot_name"] = "Greaves of the Bloodwarder", ["prio"] = "Prio: DPS Warrior",},
{["loot_id"] = "29981", ["loot_name"] = "Ethereum Life-Staff", ["prio"] = "Prio: FFA",},
{["loot_id"] = "29965", ["loot_name"] = "Girdle of the Righteous Path", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30449", ["loot_name"] = "Void Star Talisman", ["prio"] = "Prio: FFA",},
{["loot_id"] = "29962", ["loot_name"] = "Heartrazor", ["prio"] = "Prio: FFA",},
{["loot_id"] = "29966", ["loot_name"] = "Vambraces of Ending", ["prio"] = "Prio: Rogues > Feral > Hunter > Enhancer",},
{["loot_id"] = "30446", ["loot_name"] = "Solarian's Sapphire", ["prio"] = "Prio: FFA",},
{["loot_id"] = "29951", ["loot_name"] = "Star-Strider Boots", ["prio"] = "Prio: Retri",},
{["loot_id"] = "29977", ["loot_name"] = "Star-Soul Breeches", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32267", ["loot_name"] = "Boots of the Resilient", ["prio"] = "Prio: Prot Pala > Prot Warri",},
{["loot_id"] = "29972", ["loot_name"] = "Trousers of the Astromancer", ["prio"] = "Prio: FFA",},
{["loot_id"] = "29976", ["loot_name"] = "Worldstorm Gauntlets", ["prio"] = "Prio: Resto Shaman",},
{["loot_id"] = "29982", ["loot_name"] = "Wand of the Forgotten Star", ["prio"] = "Prio: Warlock/Shadow",},
-----Kael'thas
{["loot_id"] = "32405", ["loot_name"] = "Verdant Sphere", ["prio"] = "Prio: ProtP > Arcane/Ele > SV > BM/Warlock/Balance > Healer/Enha > Rogue > Warrior",},
{["loot_id"] = "30236", ["loot_name"] = "Chestguard of the Vanquished Champion", ["prio"] = "Prio: Enha > Resto/Ele/Holy Pala/Ret > Rogue/Prot Pala",},
{["loot_id"] = "30237", ["loot_name"] = "Chestguard of the Vanquished Defender", ["prio"] = "Prio: Prot Warrior > Feral > DPS Warri/Heal Priest/Resto Druid > Shadow",},
{["loot_id"] = "30238", ["loot_name"] = "Chestguard of the Vanquished Hero", ["prio"] = "Prio: Mage > Hunter > Warlock",},
{["loot_id"] = "29997", ["loot_name"] = "Band of the Ranger-General", ["prio"] = "Prio: Enha/Arms/Fury/Ret > Rogue/Hunter",},
{["loot_id"] = "29990", ["loot_name"] = "Crown of the Sun", ["prio"] = "Prio: Resto Druid/Holy Priest",},
{["loot_id"] = "29994", ["loot_name"] = "Thalassian Wildercloak", ["prio"] = "Prio: Hunter > Enhancer > Feral",},
{["loot_id"] = "29987", ["loot_name"] = "Gauntlets of the Sun King", ["prio"] = "Prio: Mage (if no Engineer)",},
{["loot_id"] = "29995", ["loot_name"] = "Leggings of Murderous Intent", ["prio"] = "Prio: BM/Ret/Fury/Arms",},
{["loot_id"] = "29996", ["loot_name"] = "Rod of the Sun King", ["prio"] = "Prio: Enhancer > Fury",},
{["loot_id"] = "29992", ["loot_name"] = "Royal Cloak of the Sunstriders", ["prio"] = "Prio: Prot Pala/Shadow > Arcane Mage",},
{["loot_id"] = "29991", ["loot_name"] = "Sunhawk Leggings", ["prio"] = "Prio: Resto Shaman > Holy Paladin",},
{["loot_id"] = "29989", ["loot_name"] = "Sunshower Light Cloak", ["prio"] = "Prio: Priest/Druid > Shaman/Paladin",},
{["loot_id"] = "29988", ["loot_name"] = "The Nexus Key", ["prio"] = "Prio: Arcane Mage > Balance/Ele",},
{["loot_id"] = "29993", ["loot_name"] = "Twinblade of the Phoenix", ["prio"] = "Prio: Ret/Arms > Hunter",},
{["loot_id"] = "29998", ["loot_name"] = "Royal Gauntlets of Silvermoon", ["prio"] = "Prio: Prot Warri > Prot Pala",},
-----
-----Hyjal
-----Thrashloot
{["loot_id"] = "32589", ["loot_name"] = "Hellfire-Encased Pendant", ["prio"] = "Prio: FFA",},
{["loot_id"] = "34010", ["loot_name"] = "Pepe's Shroud of Pacification", ["prio"] = "Prio: Prot Warri > Feral > Rest",},
{["loot_id"] = "32609", ["loot_name"] = "Boots of the Divine Light", ["prio"] = "Prio: Priest > Rest",},
{["loot_id"] = "32592", ["loot_name"] = "Chestguard of Relentless Storms", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32591", ["loot_name"] = "Choker of Serrated Blades", ["prio"] = "Prio: DD Warri, BM > Rest",},
{["loot_id"] = "34009", ["loot_name"] = "Hammer of Judgment", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32590", ["loot_name"] = "Nethervoid Cloak", ["prio"] = "Prio: Shadow > Rest",},
{["loot_id"] = "32946", ["loot_name"] = "Claw of Molten Fury", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32945", ["loot_name"] = "Fist of Molten Fury", ["prio"] = "Prio: FFA",},
-----Winterchill
{["loot_id"] = "30870", ["loot_name"] = "Cuffs of Devastation", ["prio"] = "Prio: Mage > Rest",},
{["loot_id"] = "30866", ["loot_name"] = "Blood-Stained Pauldrons", ["prio"] = "Prio: DPS Warrior > Retri > Rest",},
{["loot_id"] = "30871", ["loot_name"] = "Bracers of Martyrdom", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30872", ["loot_name"] = "Chronicle of Dark Secrets", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30863", ["loot_name"] = "Deadly Cuffs", ["prio"] = "Prio: DPS Warrior > Enha > Rest",},
{["loot_id"] = "30868", ["loot_name"] = "Rejuvenating Bracers", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30862", ["loot_name"] = "Blessed Adamantite Bracers", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30864", ["loot_name"] = "Bracers of the Pathfinder", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30861", ["loot_name"] = "Furious Shackles", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30865", ["loot_name"] = "Tracker's Blade", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30873", ["loot_name"] = "Stillwater Boots", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30869", ["loot_name"] = "Howling Wind Bracers", ["prio"] = "Prio: FFA",},
-----Anetheron
{["loot_id"] = "30888", ["loot_name"] = "Anetheron's Noose", ["prio"] = "Mage > Rest",},
{["loot_id"] = "30883", ["loot_name"] = "Pillar of Ferocity", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30882", ["loot_name"] = "Bastion of Light", ["prio"] = "Prio: Resto Schami > Rest",},
{["loot_id"] = "30881", ["loot_name"] = "Blade of Infamy", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30879", ["loot_name"] = "Don Alejandro's Money Belt", ["prio"] = "Prio: SV > Rest",},
{["loot_id"] = "30886", ["loot_name"] = "Enchanted Leather Sandals", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30878", ["loot_name"] = "Glimmering Steel Mantle", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30874", ["loot_name"] = "The Unbreakable Will", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30885", ["loot_name"] = "Archbishop's Slippers", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30887", ["loot_name"] = "Golden Links of Restoration", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30884", ["loot_name"] = "Hatefury Mantle", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30880", ["loot_name"] = "Quickstrider Moccasins", ["prio"] = "Prio: FFA",},
-----Kaz'rogal
{["loot_id"] = "30915", ["loot_name"] = "Belt of Seething Fury", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30891", ["loot_name"] = "Black Featherlight Boots", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30894", ["loot_name"] = "Blue Suede Shoes", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30918", ["loot_name"] = "Hammer of Atonement", ["prio"] = "Prio: Heal Pala > Resto Sham > Rest",},
{["loot_id"] = "30916", ["loot_name"] = "Leggings of Channeled Elements", ["prio"] = "Prio: Ele/Eule > Rest",},
{["loot_id"] = "30895", ["loot_name"] = "Angelista's Sash", ["prio"] = "Prio: Priest > Resto Druid > Rest",},
{["loot_id"] = "30889", ["loot_name"] = "Kaz'rogal's Hardened Heart", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30917", ["loot_name"] = "Razorfury Mantle", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30919", ["loot_name"] = "Valestalker Girdle", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30892", ["loot_name"] = "Beast-Tamer's Shoulders", ["prio"] = "Prio: Hunter",},
{["loot_id"] = "30893", ["loot_name"] = "Sun-Touched Chain Leggings", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30914", ["loot_name"] = "Belt of the Crescent Moon", ["prio"] = "Prio: FFA",},
-----Azgalor
{["loot_id"] = "31093", ["loot_name"] = "Gloves of the Forgotten Vanquisher", ["prio"] = "Prio: Feral > Rogue > Resto > Rest",},
{["loot_id"] = "31092", ["loot_name"] = "Gloves of the Forgotten Conqueror", ["prio"] = "Prio: Prot Pala > Warlocks > Shadow > Rest",},
{["loot_id"] = "31094", ["loot_name"] = "Gloves of the Forgotten Protector", ["prio"] = "Prio: Ele, Hunter, Fury > Rest",},
{["loot_id"] = "30899", ["loot_name"] = "Don Rodrigo's Poncho", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30901", ["loot_name"] = "Boundless Agony", ["prio"] = "Prio: BM > Rest",},
{["loot_id"] = "30900", ["loot_name"] = "Bow-Stitched Leggings", ["prio"] = "Prio: SV > Enha, Retri > Rest",},
{["loot_id"] = "30897", ["loot_name"] = "Girdle of Hope", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30896", ["loot_name"] = "Glory of the Defender", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30898", ["loot_name"] = "Shady Dealer's Pantaloons", ["prio"] = "Prio: FFA",},
-----Archimonde
{["loot_id"] = "31096", ["loot_name"] = "Helm of the Forgotten Vanquisher", ["prio"] = "Prio: Feral > Rogue > Resto > Rest",},
{["loot_id"] = "31095", ["loot_name"] = "Helm of the Forgotten Protector", ["prio"] = "Prio: Resto, Ele, SV, Warrior > Rest",},
{["loot_id"] = "31097", ["loot_name"] = "Helm of the Forgotten Conqueror", ["prio"] = "Prio: Prot Pala > Warlocks > Shadow > Rest",},
{["loot_id"] = "30909", ["loot_name"] = "Antonidas' Aegis of Rapt Concentration", ["prio"] = "Prio: Ele > Rest",},
{["loot_id"] = "30908", ["loot_name"] = "Apostle of Argus", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30906", ["loot_name"] = "Bristleblitz Striker", ["prio"] = "Prio: BM > SV > Rest",},
{["loot_id"] = "30902", ["loot_name"] = "Cataclysm's Edge", ["prio"] = "Prio: Arms > Ret > Rest",},
{["loot_id"] = "30912", ["loot_name"] = "Leggings of Eternity", ["prio"] = "Prio: Priest > Rest",},
{["loot_id"] = "30903", ["loot_name"] = "Legguards of Endless Rage", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30907", ["loot_name"] = "Mail of Fevered Pursuit", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30913", ["loot_name"] = "Robes of Rhonin", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30904", ["loot_name"] = "Savior's Grasp", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30911", ["loot_name"] = "Scepter of Purification", ["prio"] = "Prio: FFA",},
{["loot_id"] = "30910", ["loot_name"] = "Tempest of Chaos", ["prio"] = "Prio: Prot Pala > Rest",},
{["loot_id"] = "30905", ["loot_name"] = "Midnight Chestguard", ["prio"] = "Prio: Enha > Retri > Rest",},
-----
-----Black Temple
-----Thrashloot
{["loot_id"] = "32526", ["loot_name"] = "Band of Devastation", ["prio"] = "Prio: Retri > Rest",},
{["loot_id"] = "32527", ["loot_name"] = "Ring of Ancient Knowledge", ["prio"] = "Balance/Shadow/Ele* > Rest (* erst wenn alle Caster einen haben)",},
{["loot_id"] = "32528", ["loot_name"] = "Blessed Band of Karabor", ["prio"] = "Prio: Resto Druide* > Rest* (erstmal nur einen Ring)",},
{["loot_id"] = "32593", ["loot_name"] = "Treads of the Den Mother", ["prio"] = "Prio: Feral > Rest",},
{["loot_id"] = "32606", ["loot_name"] = "Girdle of the Lightbearer", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32608", ["loot_name"] = "Pillager's Gauntlets", ["prio"] = "Prio: DPS Warri > Rest",},
{["loot_id"] = "32943", ["loot_name"] = "Swiftsteel Bludgeon", ["prio"] = "Prio: FFA",},
{["loot_id"] = "34011", ["loot_name"] = "Illidari Runeshield", ["prio"] = "Prio: FFA",},
{["loot_id"] = "34012", ["loot_name"] = "Shroud of the Final Stand", ["prio"] = "Prio: Holy Pala > Rest",},
-----Naj'entus
{["loot_id"] = "32234", ["loot_name"] = "Fists of Mukoa", ["prio"] = "Prio: Enha > Rest",},
{["loot_id"] = "32240", ["loot_name"] = "Guise of the Tidal Lurker", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32248", ["loot_name"] = "Halberd of Desolation", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32238", ["loot_name"] = "Ring of Calming Waves", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32247", ["loot_name"] = "Ring of Captured Storms", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32236", ["loot_name"] = "Rising Tide", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32239", ["loot_name"] = "Slippers of the Seacaller", ["prio"] = "Prio: Mage > Warlock > Rest",},
{["loot_id"] = "32232", ["loot_name"] = "Eternium Shell Bracers", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32377", ["loot_name"] = "Mantle of Darkness", ["prio"] = "Prio: Enha > Rest",},
{["loot_id"] = "32237", ["loot_name"] = "The Maelstrom's Fury", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32241", ["loot_name"] = "Helm of Soothing Currents", ["prio"] = "Prio: Heal Pala > Rest",},
{["loot_id"] = "32243", ["loot_name"] = "Pearl Inlaid Boots", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32245", ["loot_name"] = "Tide-Stomper's Greaves", ["prio"] = "Prio: Prot Pala > Prot Warri",},
{["loot_id"] = "32242", ["loot_name"] = "Boots of Oceanic Fury", ["prio"] = "Prio: FFA",},
-----Supremus
{["loot_id"] = "32261", ["loot_name"] = "Band of the Abyssal Lord", ["prio"] = "Prio: Prot Warri > Rest",},
{["loot_id"] = "32262", ["loot_name"] = "Syphon of the Nathrezim", ["prio"] = "Prio: Enha > Rest",},
{["loot_id"] = "32251", ["loot_name"] = "Wraps of Precise Flight", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32260", ["loot_name"] = "Choker of Endless Nightmares", ["prio"] = "Prio: Rogues, Enha > Rest",},
{["loot_id"] = "32255", ["loot_name"] = "Felstone Bulwark", ["prio"] = "Prio: Holy Pala > Rest",},
{["loot_id"] = "32256", ["loot_name"] = "Waistwrap of Infinity", ["prio"] = "Prio: Shadow > Warlock > Rest",},
{["loot_id"] = "32252", ["loot_name"] = "Nether Shadow Tunic", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32250", ["loot_name"] = "Pauldrons of Abyssal Fury", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32254", ["loot_name"] = "The Brutalizer", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32253", ["loot_name"] = "Legionkiller", ["prio"] = "Prio: Prot Warri > Rest",},
{["loot_id"] = "32258", ["loot_name"] = "Naturalist's Preserving Cinch", ["prio"] = "Prio: Resto Sham > Rest",},
{["loot_id"] = "32259", ["loot_name"] = "Bands of the Coming Storm", ["prio"] = "Prio: Ele Sham > Rest",},
-----Shade of Akama
{["loot_id"] = "32513", ["loot_name"] = "Wristbands of Divine Influence", ["prio"] = "Prio: Priest > Rest",},
{["loot_id"] = "32278", ["loot_name"] = "Grips of Silent Justice", ["prio"] = "Prio: DPS Warri > Rest",},
{["loot_id"] = "32266", ["loot_name"] = "Ring of Deceitful Intent", ["prio"] = "Prio: Feral* > Rest* (*Hit Budget beachten)",},
{["loot_id"] = "32270", ["loot_name"] = "Focused Mana Bindings", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32263", ["loot_name"] = "Praetorian's Legguards", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32265", ["loot_name"] = "Shadow-Walker's Cord", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32264", ["loot_name"] = "Shoulders of the Hidden Predator", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32361", ["loot_name"] = "Blind-Seers Icon", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32271", ["loot_name"] = "Kilt of Immortal Nature", ["prio"] = "Prio: Rest Druid > Resto Shami > Holy Pala > Rest",},
{["loot_id"] = "32268", ["loot_name"] = "Myrmidon's Treads", ["prio"] = "Prio: Prot Warri > Rest",},
{["loot_id"] = "32273", ["loot_name"] = "Amice of Brilliant Light", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32276", ["loot_name"] = "Flashfire Girdle", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32275", ["loot_name"] = "Spiritwalker Gauntlets", ["prio"] = "Prio: Resto SHam > Holy Pala > Rest",},
{["loot_id"] = "32279", ["loot_name"] = "The Seeker's Wristguards", ["prio"] = "Prio: FFA",},
-----Teron Gorefiend
{["loot_id"] = "32328", ["loot_name"] = "Botanist's Gloves of Growth", ["prio"] = "Prio: Resto Druid > Rest",},
{["loot_id"] = "32329", ["loot_name"] = "Cowl of Benevolence", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32348", ["loot_name"] = "Soul Cleaver", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32512", ["loot_name"] = "Girdle of Lordaeron's Fallen", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32324", ["loot_name"] = "Insidious Bands", ["prio"] = "Prio: Rogue > Hunter > Rest",},
{["loot_id"] = "32325", ["loot_name"] = "Rifle of the Stoic Guardian", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32510", ["loot_name"] = "Softstep Boots of Tracking", ["prio"] = "Prio: Enha > Rest",},
{["loot_id"] = "32280", ["loot_name"] = "Gauntlets of Enforcement", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32327", ["loot_name"] = "Robe of the Shadow Council", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32323", ["loot_name"] = "Shadowmoon Destroyer's Drape", ["prio"] = "Prio: DPS Warri, Rogue, Enha > Rest",},
{["loot_id"] = "32326", ["loot_name"] = "Twisted Blades of Zarak", ["prio"] = "Prio: DPS Warri, Rogue > Rest",},
-----Gurtogg
{["loot_id"] = "32339", ["loot_name"] = "Belt of Primal Majesty", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32501", ["loot_name"] = "Shadowmoon Insignia", ["prio"] = "Prio: Feral > Prot Warrior > Prot Pala > Rest",},
{["loot_id"] = "32337", ["loot_name"] = "Shroud of Forgiveness", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32335", ["loot_name"] = "Unstoppable Aggressor's Ring", ["prio"] = "Prio: DPS Warrior > Rest",},
{["loot_id"] = "32340", ["loot_name"] = "Garments of Temperance", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32333", ["loot_name"] = "Girdle of Stability", ["prio"] = "Prio: Prot Warri > Prot Pala",},
{["loot_id"] = "32269", ["loot_name"] = "Messenger of Fate", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32344", ["loot_name"] = "Staff of Immaculate Recovery", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32343", ["loot_name"] = "Wand of Prismatic Focus", ["prio"] = "Prio: Shadow > Rest",},
{["loot_id"] = "32334", ["loot_name"] = "Vest of Mounting Assault", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32338", ["loot_name"] = "Blood-Cursed Shoulderpads", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32341", ["loot_name"] = "Leggings of Divine Retribution", ["prio"] = "Prio: Fury > Arms > Rest",},
{["loot_id"] = "32342", ["loot_name"] = "Girdle of Mighty Resolve", ["prio"] = "Prio: Prot Paladin",},
-----Reliquary
{["loot_id"] = "32345", ["loot_name"] = "Dreadboots of the Legion", ["prio"] = "Prio: DPS Warri > Rest",},
{["loot_id"] = "32350", ["loot_name"] = "Touch of Inspiration", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32353", ["loot_name"] = "Gloves of Unfailing Faith", ["prio"] = "Prio: Holy Pala > Priest > Rest",},
{["loot_id"] = "32347", ["loot_name"] = "Grips of Damnation", ["prio"] = "Prio: Enha > Ret > Rest",},
{["loot_id"] = "32332", ["loot_name"] = "Torch of the Damned", ["prio"] = "Prio: Retri > Rest",},
{["loot_id"] = "32346", ["loot_name"] = "Boneweave Girdle", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32517", ["loot_name"] = "The Wavemender's Mantle", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32354", ["loot_name"] = "Crown of Empowered Fate", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32363", ["loot_name"] = "Naaru-Blessed Life Rod", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32349", ["loot_name"] = "Translucent Spellthread Necklace", ["prio"] = "Prio: Warlock > Rest",},
{["loot_id"] = "32362", ["loot_name"] = "Pendant of Titans", ["prio"] = "Prio: Prot Warri > Feral",},
{["loot_id"] = "32351", ["loot_name"] = "Elunite Empowered Bracers", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32352", ["loot_name"] = "Naturewarden's Treads", ["prio"] = "Prio: Balance Druid > Rest",},
-----Shahraz
{["loot_id"] = "31101", ["loot_name"] = "Pauldrons of the Forgotten Conqueror", ["prio"] = "Prio: Prot Pala > Warlocks > Rest",},
{["loot_id"] = "31102", ["loot_name"] = "Pauldrons of the Forgotten Vanquisher", ["prio"] = "Prio: Feral > Rogue > Resto > Rest",},
{["loot_id"] = "31103", ["loot_name"] = "Pauldrons of the Forgotten Protector", ["prio"] = "Prio: Resto, Ele, Hunter, Warrior > Enha",},
{["loot_id"] = "32365", ["loot_name"] = "Heartshatter Breastplate", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32369", ["loot_name"] = "Blade of Savagery", ["prio"] = "Prio: Rogue, Prot Warri* > Rest",},
{["loot_id"] = "32367", ["loot_name"] = "Leggings of Devastation", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32370", ["loot_name"] = "Nadina's Pendant of Purity", ["prio"] = "Prio: Holy Pala > Rest",},
{["loot_id"] = "32366", ["loot_name"] = "Shadowmaster's Boots", ["prio"] = "Prio: Rogue > Ret, Hunter > Enha > Rest",},
-----Illidary Council
{["loot_id"] = "31100", ["loot_name"] = "Leggings of the Forgotten Protector", ["prio"] = "Prio: Resto, BM, Warrior > Rest",},
{["loot_id"] = "31098", ["loot_name"] = "Leggings of the Forgotten Conqueror", ["prio"] = "Prio: Prot Pala > Warlocks > Shadow > Rest",},
{["loot_id"] = "31099", ["loot_name"] = "Leggings of the Forgotten Vanquisher", ["prio"] = "Prio: Feral > Rogue > Resto > Rest",},
{["loot_id"] = "32519", ["loot_name"] = "Belt of Divine Guidance", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32376", ["loot_name"] = "Forest Prowler's Helm", ["prio"] = "Prio: Ret > Hunter > Rest",},
{["loot_id"] = "32331", ["loot_name"] = "Cloak of the Illidari Council", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32373", ["loot_name"] = "Helm of the Illidari Shatterer", ["prio"] = "Prio: DPS Warri > Retri",},
{["loot_id"] = "32505", ["loot_name"] = "Madness of the Betrayer", ["prio"] = "Prio: FFA, aber abhängig von derzeitigen Trinkets (ZA Trinket ist oft besser)",},
{["loot_id"] = "32518", ["loot_name"] = "Veil of Turning Leaves", ["prio"] = "Prio: FFA",},
-----Illidan
{["loot_id"] = "32837", ["loot_name"] = "Warglaive of Azzinoth", ["prio"] = "lol",},
{["loot_id"] = "32838", ["loot_name"] = "Warglaive of Azzinoth", ["prio"] = "lol",},
{["loot_id"] = "31089", ["loot_name"] = "Chestguard of the Forgotten Conqueror", ["prio"] = "Prio: Prot Pala > Shadow > Rest",},
{["loot_id"] = "31091", ["loot_name"] = "Chestguard of the Forgotten Protector", ["prio"] = "Prio: Resto, Ele, Hunter, Warrior > Enha",},
{["loot_id"] = "31090", ["loot_name"] = "Chestguard of the Forgotten Vanquisher", ["prio"] = "Prio: Feral > Rogue > Rest",},
{["loot_id"] = "32374", ["loot_name"] = "Zhar'doom, Greatstaff of the Devourer", ["prio"] = "Prio: Shadow > Destro > Affli/Mage > Balance > Ele",},
{["loot_id"] = "32375", ["loot_name"] = "Bulwark of Azzinoth", ["prio"] = "Prio: Prot Warri > Prot Pala",},
{["loot_id"] = "32500", ["loot_name"] = "Crystal Spire of Karabor", ["prio"] = "*Prio:  Priest, Resto Sham > Holy Pala > Rest *bisherige MH prüfen",},
{["loot_id"] = "32336", ["loot_name"] = "Black Bow of the Betrayer", ["prio"] = "Prio: SV > BM",},
{["loot_id"] = "32521", ["loot_name"] = "Faceplate of the Impenetrable", ["prio"] = "Prio: Prot Warri > Prot Pala",},
{["loot_id"] = "32525", ["loot_name"] = "Cowl of the Illidari High Lord", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32235", ["loot_name"] = "Cursed Vision of Sargeras", ["prio"] = "Prio: Enha > BM, Fury > Rest",},
{["loot_id"] = "32496", ["loot_name"] = "Memento of Tyrande", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32471", ["loot_name"] = "Shard of Azzinoth", ["prio"] = "Prio: FFA",},
{["loot_id"] = "32524", ["loot_name"] = "Shroud of the Highborne", ["prio"] = "Caster > Rest (gibt jetzt Alternativen)",},
{["loot_id"] = "32483", ["loot_name"] = "The Skull of Gul'dan", ["prio"] = "Prio: Warlock > Rest",},
{["loot_id"] = "32497", ["loot_name"] = "Stormrage Signet Ring", ["prio"] = "Prio: Rogue*, Fury*, Enha* > Rest",},
-----
-----Sunwell Plateau
-----Thrashloot
{["loot_id"] = "35733", ["loot_name"] = "Ring of Harmonic Beauty", ["prio"] = "Prio: soon",},
{["loot_id"] = "34351", ["loot_name"] = "Tranquil Majesty Wraps", ["prio"] = "Prio: soon",},
{["loot_id"] = "34348", ["loot_name"] = "Wand of Cleansing Light", ["prio"] = "Prio: soon",},
{["loot_id"] = "34183", ["loot_name"] = "Shivering Felspine", ["prio"] = "Prio: soon",},
{["loot_id"] = "34346", ["loot_name"] = "Mounting Vengeance", ["prio"] = "Prio: soon",},
{["loot_id"] = "34350", ["loot_name"] = "Gauntlets of the Ancient Shadowmoon", ["prio"] = "Prio: soon",},
{["loot_id"] = "34347", ["loot_name"] = "Wand of the Demonsoul", ["prio"] = "Prio: soon",},
-----Kalecgos
{["loot_id"] = "34852", ["loot_name"] = "Bracers of the Forgotten Vanquisher", ["prio"] = "Prio: soon",},
{["loot_id"] = "34851", ["loot_name"] = "Bracers of the Forgotten Protector", ["prio"] = "Prio: soon",},
{["loot_id"] = "34848", ["loot_name"] = "Bracers of the Forgotten Conqueror", ["prio"] = "Prio: soon",},
{["loot_id"] = "34167", ["loot_name"] = "Legplates of the Holy Juggernaut", ["prio"] = "Prio: soon",},
{["loot_id"] = "34170", ["loot_name"] = "Pantaloons of Calming Strife", ["prio"] = "Prio: soon",},
{["loot_id"] = "34168", ["loot_name"] = "Starstalker Legguards", ["prio"] = "Prio: soon",},
{["loot_id"] = "34166", ["loot_name"] = "Band of Lucent Beams", ["prio"] = "Prio: soon",},
{["loot_id"] = "34169", ["loot_name"] = "Breeches of Natural Aggression", ["prio"] = "Prio: soon",},
{["loot_id"] = "34165", ["loot_name"] = "Fang of Kalecgos", ["prio"] = "Prio: soon",},
{["loot_id"] = "34164", ["loot_name"] = "Dragonscale-Encrusted Longblade", ["prio"] = "Prio: soon",},
-----Brutallus
{["loot_id"] = "34853", ["loot_name"] = "Belt of the Forgotten Conqueror", ["prio"] = "Prio: soon",},
{["loot_id"] = "34854", ["loot_name"] = "Belt of the Forgotten Protector", ["prio"] = "Prio: soon",},
{["loot_id"] = "34855", ["loot_name"] = "Belt of the Forgotten Vanquisher", ["prio"] = "Prio: soon",},
{["loot_id"] = "34177", ["loot_name"] = "Clutch of Demise", ["prio"] = "Prio: soon",},
{["loot_id"] = "34180", ["loot_name"] = "Felfury Legplates", ["prio"] = "Prio: soon",},
{["loot_id"] = "34179", ["loot_name"] = "Heart of the Pit", ["prio"] = "Prio: soon",},
{["loot_id"] = "34181", ["loot_name"] = "Leggings of Calamity", ["prio"] = "Prio: soon",},
{["loot_id"] = "34176", ["loot_name"] = "Reign of Misery", ["prio"] = "Prio: soon",},
{["loot_id"] = "34178", ["loot_name"] = "Collar of the Pit Lord", ["prio"] = "Prio: soon",},
-----Felmyst
{["loot_id"] = "34857", ["loot_name"] = "Boots of the Forgotten Protector", ["prio"] = "Prio: soon",},
{["loot_id"] = "34856", ["loot_name"] = "Boots of the Forgotten Conqueror", ["prio"] = "Prio: soon",},
{["loot_id"] = "34858", ["loot_name"] = "Boots of the Forgotten Vanquisher", ["prio"] = "Prio: soon",},
{["loot_id"] = "34184", ["loot_name"] = "Brooch of the Highborne", ["prio"] = "Prio: soon",},
{["loot_id"] = "34186", ["loot_name"] = "Chain Links of the Tumultuous Storm", ["prio"] = "Prio: soon",},
{["loot_id"] = "34185", ["loot_name"] = "Sword Breaker's Bulwark", ["prio"] = "Prio: soon",},
{["loot_id"] = "34352", ["loot_name"] = "Borderland Fortress Grips", ["prio"] = "Prio: soon",},
{["loot_id"] = "34182", ["loot_name"] = "Grand Magister's Staff of Torrents", ["prio"] = "Prio: soon",},
{["loot_id"] = "34188", ["loot_name"] = "Leggings of the Immortal Night", ["prio"] = "Prio: soon",},
-----Twins
{["loot_id"] = "35290", ["loot_name"] = "Sin'dorei Pendant of Conquest", ["prio"] = "Prio: soon",},
{["loot_id"] = "35291", ["loot_name"] = "Sin'dorei Pendant of Salvation", ["prio"] = "Prio: soon",},
{["loot_id"] = "35292", ["loot_name"] = "Sin'dorei Pendant of Triumph", ["prio"] = "Prio: soon",},
{["loot_id"] = "34206", ["loot_name"] = "Book of Highborne Hymns", ["prio"] = "Prio: soon",},
{["loot_id"] = "34204", ["loot_name"] = "Amulet of Unfettered Magics", ["prio"] = "Prio: soon",},
{["loot_id"] = "34189", ["loot_name"] = "Band of Ruinous Delight", ["prio"] = "Prio: soon",},
{["loot_id"] = "34196", ["loot_name"] = "Golden Bow of Quel'Thalas", ["prio"] = "Prio: soon",},
{["loot_id"] = "34202", ["loot_name"] = "Shawl of Wonderment", ["prio"] = "Prio: soon",},
{["loot_id"] = "34193", ["loot_name"] = "Spaulders of the Thalassian Savior", ["prio"] = "Prio: soon",},
{["loot_id"] = "34210", ["loot_name"] = "Amice of the Convoker", ["prio"] = "Prio: soon",},
{["loot_id"] = "34199", ["loot_name"] = "Archon's Gavel", ["prio"] = "Prio: soon",},
{["loot_id"] = "34203", ["loot_name"] = "Grip of Mannoroth", ["prio"] = "Prio: soon",},
{["loot_id"] = "34194", ["loot_name"] = "Mantle of the Golden Forest", ["prio"] = "Prio: soon",},
{["loot_id"] = "34195", ["loot_name"] = "Shoulderpads of Vehemence", ["prio"] = "Prio: soon",},
{["loot_id"] = "34209", ["loot_name"] = "Spaulders of Reclamation", ["prio"] = "Prio: soon",},
{["loot_id"] = "34190", ["loot_name"] = "Crimson Paragon's Cover", ["prio"] = "Prio: soon",},
{["loot_id"] = "34208", ["loot_name"] = "Equilibrium Epaulets", ["prio"] = "Prio: soon",},
{["loot_id"] = "34192", ["loot_name"] = "Pauldrons of Perseverance", ["prio"] = "Prio: soon",},
{["loot_id"] = "34197", ["loot_name"] = "Shiv of Exsanguination", ["prio"] = "Prio: soon",},
{["loot_id"] = "34205", ["loot_name"] = "Shroud of Redeemed Souls", ["prio"] = "Prio: soon",},
{["loot_id"] = "34198", ["loot_name"] = "Stanchion of Primal Instinct", ["prio"] = "Prio: soon",},
-----Mu'ru
{["loot_id"] = "35283", ["loot_name"] = "Sin'dorei Band of Salvation", ["prio"] = "Prio: soon",},
{["loot_id"] = "35282", ["loot_name"] = "Sin'dorei Band of Dominance", ["prio"] = "Prio: soon",},
{["loot_id"] = "35284", ["loot_name"] = "Sin'dorei Band of Triumph", ["prio"] = "Prio: soon",},
{["loot_id"] = "34229", ["loot_name"] = "Garments of Serene Shores", ["prio"] = "Prio: soon",},
{["loot_id"] = "34240", ["loot_name"] = "Gauntlets of the Soothed Soul", ["prio"] = "Prio: soon",},
{["loot_id"] = "34211", ["loot_name"] = "Harness of Carnal Instinct", ["prio"] = "Prio: soon",},
{["loot_id"] = "34214", ["loot_name"] = "Muramasa", ["prio"] = "Prio: soon",},
{["loot_id"] = "34213", ["loot_name"] = "Ring of Hardened Resolve", ["prio"] = "Prio: soon",},
{["loot_id"] = "34230", ["loot_name"] = "Ring of Omnipotence", ["prio"] = "Prio: soon",},
{["loot_id"] = "34233", ["loot_name"] = "Robes of Faltered Light", ["prio"] = "Prio: soon",},
{["loot_id"] = "34429", ["loot_name"] = "Shifting Naaru Sliver", ["prio"] = "Prio: soon",},
{["loot_id"] = "34428", ["loot_name"] = "Steely Naaru Sliver", ["prio"] = "Prio: soon",},
{["loot_id"] = "34231", ["loot_name"] = "Aegis of Angelic Fortune", ["prio"] = "Prio: soon",},
{["loot_id"] = "34427", ["loot_name"] = "Blackened Naaru Sliver", ["prio"] = "Prio: soon",},
{["loot_id"] = "34232", ["loot_name"] = "Fel Conqueror Raiments", ["prio"] = "Prio: soon",},
{["loot_id"] = "34430", ["loot_name"] = "Glimmering Naaru Sliver", ["prio"] = "Prio: soon",},
{["loot_id"] = "34216", ["loot_name"] = "Heroic Judicator's Chestguard", ["prio"] = "Prio: soon",},
{["loot_id"] = "34234", ["loot_name"] = "Shadowed Gauntlets of Paroxysm", ["prio"] = "Prio: soon",},
{["loot_id"] = "34212", ["loot_name"] = "Sunglow Vest", ["prio"] = "Prio: soon",},
{["loot_id"] = "34228", ["loot_name"] = "Vicious Hawkstrider Hauberk", ["prio"] = "Prio: soon",},
{["loot_id"] = "34215", ["loot_name"] = "Warharness of Reckless Fury", ["prio"] = "Prio: soon",},
-----Kil'Jaeden
{["loot_id"] = "34334", ["loot_name"] = "Thori'dal, the Stars' Fury", ["prio"] = "Prio: soon",},
{["loot_id"] = "34344", ["loot_name"] = "Handguards of Defiled Worlds", ["prio"] = "Prio: soon",},
{["loot_id"] = "34332", ["loot_name"] = "Cowl of Gul'dan", ["prio"] = "Prio: soon",},
{["loot_id"] = "34340", ["loot_name"] = "Dark Conjuror's Collar", ["prio"] = "Prio: soon",},
{["loot_id"] = "34335", ["loot_name"] = "Hammer of Sanctification", ["prio"] = "Prio: soon",},
{["loot_id"] = "34342", ["loot_name"] = "Handguards of the Dawn", ["prio"] = "Prio: soon",},
{["loot_id"] = "34336", ["loot_name"] = "Sunflare", ["prio"] = "Prio: soon",},
{["loot_id"] = "34341", ["loot_name"] = "Borderland Paingrips", ["prio"] = "Prio: soon",},
{["loot_id"] = "34345", ["loot_name"] = "Crown of Anasterian", ["prio"] = "Prio: soon",},
{["loot_id"] = "34337", ["loot_name"] = "Golden Staff of the Sin'dorei", ["prio"] = "Prio: soon",},
{["loot_id"] = "34243", ["loot_name"] = "Helm of Burning Righteousness", ["prio"] = "Prio: soon",},
{["loot_id"] = "34242", ["loot_name"] = "Tattered Cape of Antonidas", ["prio"] = "Prio: soon",},
{["loot_id"] = "34343", ["loot_name"] = "Thalassian Ranger Gauntlets", ["prio"] = "Prio: soon",},
{["loot_id"] = "34241", ["loot_name"] = "Cloak of Unforgivable Sin", ["prio"] = "Prio: soon",},
{["loot_id"] = "34333", ["loot_name"] = "Coif of Alleria", ["prio"] = "Prio: soon",},
{["loot_id"] = "34245", ["loot_name"] = "Cover of Ursol the Wise", ["prio"] = "Prio: soon",},
{["loot_id"] = "34339", ["loot_name"] = "Cowl of Light's Purity", ["prio"] = "Prio: soon",},
{["loot_id"] = "34329", ["loot_name"] = "Crux of the Apocalypse", ["prio"] = "Prio: soon",},
{["loot_id"] = "34244", ["loot_name"] = "Duplicitous Guise", ["prio"] = "Prio: soon",},
{["loot_id"] = "34331", ["loot_name"] = "Hand of the Deceiver", ["prio"] = "Prio: soon",},
{["loot_id"] = "34247", ["loot_name"] = "Apolyon, the Soul-Render", ["prio"] = "Prio: soon",},
}
